enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"

patches-version = "dev"

build-mode = "both"
arch = "both"

rv-brand = "ReVanced Extended"

[YouTube Revanced Extended]
app-name = "YouTube RVX"
version = "20.21.37"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
excluded-patches = "'Custom header for YouTube'"
included-patches = "'Visual preferences icons for YouTube' 'Return YouTube Username'"
patcher-args = "-e 'Custom branding' -OcustomName='YouTube RVX' -OcustomIcon='Vanced Black' -e 'Theme' -OlightThemeBackgroundColor=#FFF9F9F9"

[YouTube Music Revanced Extended]
app-name = "YT Music RVX"
version = "8.30.54"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
excluded-patches = "'Custom header for YouTube Music'"
included-patches = "'Visual preferences icons for YouTube Music' 'Return YouTube Username' 'Disable music video in album'"
patcher-args = "-e 'Custom branding' -OcustomName='YT Music RVX' -OcustomIcon='Vanced Black'"
